Operator registration
TreinaDev/pagamentos-beta pull request #12
Opened 2021-11-17 19:29 UTC by renatodinizc

Administrador pode cadastrar operador com dominio pagapaga.com.br

2021-11-18 14:24 UTC, joaorsalmeida commented on app/controllers/admins_controller.rb
> +    if admin_signed_in?
Nao vale tratar o `else` aqui? Ou então bloquear esse acesso para somente admins?

2021-11-18 14:25 UTC, joaorsalmeida requested changes
Apesar de já agregar valor, me parece que vale a pena adicionar ao menos mais um cenário de teste que trata o caso de não administradores acessando a rota `admins/show_profile`

2021-11-18 18:08 UTC, gabdemiranda commented on app/controllers/admins_controller.rb
> +    if admin_signed_in?
Foi uma solução temporária antes de colocar a segurança atráves do bloqueio da action no controller, vamos puxar uma branch só para aplicar as restrições de acesso e substituir as "gambiarras" temporárias para avançar mais rápido.

2021-11-22 21:45 UTC, joaorsalmeida approved these changes

2021-11-23 05:43 UTC, merged