Login e signup do gerente da empresa
TreinaDev/pagamentos-beta pull request #13
Opened 2021-11-17 20:34 UTC by gabdemiranda

Adicionados testes e botão para acesso a página de login e cadastro do usuário "gerente de uma empresa"

2021-11-18 14:28 UTC, joaorsalmeida commented on app/models/manager.rb
> +      errors.add(:email, "Domínio inválido") if (domain == "gmail.com" || domain == "hotmail.com" || domain == "yahoo.com")
Essa lista pode ser bem mais ampla, concordam?

Vale a pena isolar isso em outro lugar, num arquivo de configuração por exemplo. Leiam esse trecho do Guides como referência: https://guides.rubyonrails.org/configuring.html#custom-configuration

Mas isso pode ser feito em outro momento, criem um novo item do backlog para isso.

2021-11-18 14:30 UTC, joaorsalmeida requested changes
Acredito que os links para chegar no cadastro poderiam ser um pouco mais fáceis de entender.  Usando os nomes padrão do Devise me parece confuso. Clicar em `Login` e depois em `Sign Up` para criar uma conta de acesso como cliente? 

Esse é outro ponto que me chamou atenção mas que é ok se o time está de acordo. Nem sempre é o gerente de uma empresa que vai acessar a plataforma. Isso foi um exemplo no contexto do projeto. Pode ser um funcionario do financeiro ou ate mesmo de tecnologia, concordam? Me parece que o `manager` de vocês é muito mais um `customer` de forma geral.

2021-11-18 19:08 UTC, gabdemiranda commented on app/models/manager.rb
> +      errors.add(:email, "Domínio inválido") if (domain == "gmail.com" || domain == "hotmail.com" || domain == "yahoo.com")
Adicionamos no backlog a pauta de aumentar a lista com o link de referência do guides para auxiliar!

2021-11-22 21:46 UTC, joaorsalmeida approved these changes

2021-11-23 05:44 UTC, merged