Client access
TreinaDev/pagamentos-beta pull request #16
Opened 2021-11-18 20:30 UTC by renatodinizc

Implementação de requisição de cadastro completo de empresa após login do cliente

2021-11-19 13:25 UTC, joaorsalmeida requested changes
Preciso que revejam o tratamento de autenticação e autorização nos controllers. 

Além disso deixei umas dúvidas que precisam ser vistas com todo time para garantir que está tudo ok.

2021-11-19 13:25 UTC, joaorsalmeida commented on app/controllers/companies_controller.rb
> +  def new
Falta tratar autenticação/autorização aqui, não acham?

2021-11-19 13:25 UTC, joaorsalmeida commented on app/models/company.rb
> +  belongs_to :manager
Acho que essa associação vai dar problemas lá na frente, quando quisermos add mais funcionários à empresa. A nao ser que vocês criem outro model do Devise para ser usuários 'comuns' de uma empresa... 🤔  

É algo pra pensar e se for o caso rever o backlog e planejar os ajustes.

2021-11-19 13:25 UTC, joaorsalmeida commented on app/views/companies/new.html.erb
> +  <%= @company.errors.full_messages_for(:corporate_name)[0] %>
FAz sentido mostrar só o item zero? Fiquei curioso aqui com essa ideia....

2021-11-21 12:54 UTC, renatodinizc commented on app/models/company.rb
> +  belongs_to :manager
Eae João, é isso mesmo! O cliente terá dois tipos de usuários: o Manager (responsável por registrar a empresa na plataforma de pagamentos e controlar o acesso de novos funcionários) e o Employee (terá as demais funcionalidades similares).

2021-11-22 11:48 UTC, renatodinizc commented
Pedi para fechar este PR para implementar algumas funcionalidade adicionais que necessitam desta branch. Ao finalizar, farei nova requisição de PR

2021-11-22 11:48 UTC, closed without merging